name: Print Pull Request Context
# workflow triggers can be different and we can make an array of them, hence this will respond for all of them
on: [workflow_dispatch, push, pull_request]
# also there are different activity types in pull_request for example, so ther is a different way to do it:
# on:
#  workflow_dispatch:
#  pull_request:
#    types: [opened, edit, reopened]
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Print context
        run: echo "${{ toJSON(github.event) }}"